name: Install Dependencies
inputs:
  node-version:
    required: false
    default: '20.x'

runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v4
    with:
      node-version: ${{ inputs.node-version }}
      cache: yarn
      cache-dependency-path: yarn.lock
      check-latest: true
  - name: Install Dependencies
    run: yarn install --frozen-lockfile --non-interactive --ignore-scripts
    shell: bash
