/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by js1 build metro-ts-defs / yarn run build-ts-defs
 * @generated SignedSource<<b9a3983a569cad0ee639078690423cf1>>
 *
 * This file was translated from Flow by scripts/generateTypeScriptDefinitions.js
 * Original file: packages/metro-file-map/src/plugins/dependencies/dependencyExtractor.js
 * To regenerate, run:
 *   js1 build metro-ts-defs (internal) OR
 *   yarn run build-ts-defs (OSS) 
 */

declare const dependencyExtractor: {
  extract(code: string): Set<string>;
};

export = dependencyExtractor;
