commands:
  yarn_install:
    description: "A wrapper to yarn install with caching"
    parameters:
      working_directory:
        type: string
        default: ""
    steps:
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            # Fallback in case checksum fails
            - dependencies-{{ .Branch }}-
      - run:
          command: NPM_TOKEN= yarn --no-progress
          working_directory: << parameters.working_directory >>
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

  yarn_run:
    description: "A wrapper to execute yarn commands in a safe way"
    parameters:
      working_directory:
        type: string
        default: ""
      command:
        type: string
    steps:
      - run:
          command: NPM_TOKEN= yarn run << parameters.command >>
          working_directory: << parameters.working_directory >>

  deploy_website:
    steps:
      - run: git config --global user.email "metro-bot@users.noreply.github.com"
      - run: git config --global user.name "Website Deployment Script"
      - run: echo "machine github.com login metro-bot password $GITHUB_TOKEN" > ~/.netrc
      - yarn_install:
          working_directory: website
      - yarn_run:
          command: write-translations
          working_directory: website
      # crowdin install
      - run: sudo apt-get install default-jre
      - run: wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
      - run: sudo dpkg -i crowdin.deb
      # translations upload/download
      - run: crowdin --config crowdin.yaml upload sources --auto-update -b master
      - run: crowdin --config crowdin.yaml download -b master
      # build and publish website      
      - yarn_run:
          command: publish-gh-pages
          working_directory: website

version: 2.1
jobs:
  run-js-checks:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - yarn_install
      - yarn_run:
          command: test-ci

  test-node-10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - yarn_install
      - yarn_run:
          command: jest

  test-node-8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - yarn_install
      - yarn_run:
          command: jest

  publish-to-npm:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - yarn_install
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm run publish
      - run: rm ~/.npmrc

  test-and-deploy-website:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - deploy_website

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - run-js-checks
      - test-node-8
      - test-node-10
      - test-and-deploy-website
      - publish-to-npm:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
