/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by js1 build metro-ts-defs / yarn run build-ts-defs
 */

declare const dependencyExtractor: {
  extract(code: string): Set<string>;
};

export = dependencyExtractor;
